### PR TITLE
Added an awaitable Promise wrapper for getCookies

### PR DESCRIPTION
**Pull request by rubengmurray**

### CODE REVIEW

**Comment by textbook** [comment]
Note Node comes with an implementation of that wrapper, as I show in https://stackoverflow.com/a/65265955/3001761

**Comment by rubengmurray** [comment]
> Note Node comes with an implementation of that wrapper, as I show in https://stackoverflow.com/a/65265955/3001761

Thanks for updating this PR with the link @textbook - I believe that wrapper will solve all cases except for where `profile` is required, as `profile` becomes the last argument in the function call.

Still, given this PR has been hanging around for 9 months, I'm sure your answer will help many.

**Comment by suntong** [comment]
Now this PR has been about a year

**Comment by rubengmurray** [comment]
> Now this PR has been about a year

Yeah this is no longer maintained by the owner unfortunately.

**Comment by suntong** [comment]
Yeah, noticed that as well. 

I found your PR merged in at https://github.com/paragbaxi/chrome-cookies-secure, FTR.

**Comment by rubengmurray** [comment]
Had no idea about that fork. Cheers

**Comment by paragbaxi** [comment]
☺ Looking to get this in Playwright.

**Comment by rubengmurray** [comment]
Need any assistance? I'm pretty invested in this package and still use it everyday. Hadn't heard of `playwright`... until now. How are you going about raising?

**Comment by bertrandom** [comment]
Hi, sorry for the radio silence here - don't have a lot of great excuses but let's just say toddler + COVID has made me less attentive to my repos than I'd like to be. @rubengmurray would you be interested in taking this module over if you have the bandwidth for it?

**Comment by paragbaxi** [comment]
self/family first! i added you @rubengmurray as a contributor

**Comment by rubengmurray** [comment]
Yeah I'd be happy to assist with this going forward as a maintainer. 

What's the best way to get the latest code changes on the existing npm package? It would be good for continuity if existing packager users could benefit from updates...

Can we merge `paragbaxi/chrome-cookies-secure` into here and @paragbaxi & I become maintainers?

**Comment by bertrandom** [comment]
@rubengmurray @paragbaxi Can you give me your npm usernames and I can add you as maintainers there and here and you can take it from there? Thanks.

**Comment by rubengmurray** [comment]
> @rubengmurray @paragbaxi Can you give me your npm usernames and I can add you as maintainers there and here and you can take it from there? Thanks.

Same username on npm, `rubengmurray`

**Comment by paragbaxi** [comment]
> @rubengmurray @paragbaxi Can you give me your npm usernames and I can add you as maintainers there and here and you can take it from there? Thanks.

paragbaxi

**Comment by paragbaxi** [comment]
> Can we merge `paragbaxi/chrome-cookies-secure` into here and @paragbaxi & I become maintainers?

Makes sense.

**Comment by bertrandom** [comment]
@rubengmurray @paragbaxi Invites sent, please merge/modify in whatever way you see fit. Thanks! Let me know if there's anything else you need.

**Comment by rubengmurray** [comment]
@paragbaxi it looks like your version is just this repo with:

- https://github.com/bertrandom/chrome-cookies-secure/pull/22/files
- https://github.com/bertrandom/chrome-cookies-secure/pull/21/files

Perhaps just easier to merge these two PRs in here rather than merge repos or your `master` to this... if you're happy with that on reading this then please do merge 👍  and we'll crack on over the next few weeks reviewing the open PRs for this repo?

**Comment by rubengmurray** [comment]
@paragbaxi are you happy to merge / approve this in? I'm wary of doing it myself given it's my own work.

**Comment by paragbaxi** [comment]
My bad for the delay. Excited to see movement here. Yeah I can do it.

**Comment by paragbaxi** [comment]
noticed the line break. any style we're following? i prefer prettier default

**Comment by rubengmurray** [comment]
> noticed the line break. any style we're following? i prefer prettier default

Prettier default is good with me 👍 good suggestion

Perhaps a separate PR with Prettier config applied the entire repo is in order?

**Pull request merged**
