### PR TITLE
bump: `sqlite`, `keytar` dependencies to fix node v18 build issue

### PR DESCRIPTION
**Pull request by ttzztztz**
# Background

This PR fixes an issue in Node v18, it will build fail due to legacy `sqlite` and `keytar` dependencies.

Screen Shot 2022-05-05 at 20 35 29

I fixed by updating those dependencies to the latest version, after that, `npm install` won't emit errors anymore in `node v18.0.0`

Screen Shot 2022-05-05 at 20 43 56

# Test

Run some scripts in `example/`, no errors emitted

Screen Shot 2022-05-05 at 20 45 45

### CODE REVIEW

**Comment by ttzztztz** [comment]
@bertrandom Hi, could you help to review this PR and publish a new version of that? This `chrome-cookies-secure` library is a really critial part of my project. Thanks

**Comment by rubengmurray** [comment]
Hi @ttzztztz

I'll take a look this evening 👀

**Comment by rubengmurray** [comment]
@ttzztztz can you guarantee this change doesn't break any working implementations of `chrome-cookies-secure`? Minimum version of Node this currently works with is `8.17.0` based on my quick testing locally (running `npm i`).

However I'm no longer using this pro-actively in my own work. Would you be able to run your own project using these latest dependencies with Node `8.17.0` to see if it works as expected?

We can of course merge this as a breaking change but we should probably bump the major version to indicate that.

What version of Node were you using with this package before Node 18?

**Comment by ttzztztz** [comment]
Hi @rubengmurray .I’ve been using my branch on Node.JS v18 for few days, and nothing errors were found. I think that it would work properly. I agree that we could publish a new major version for this change.

Since I always update my Node.JS to the latest, I used this package on Node.JS from v15 to v17 on macOS platform, and everything works fine before v18 :-)

**Comment by rubengmurray** [comment]
I've managed to get a bit more clarity from a macOS perspective running locally and it does appear this breaks version 8.17.0 support with a fresh `package-lock.json` generated.

>`10.22.0` is definitely working well on `puppeteer` cookie retrieval & standard as is `18.1.0`

I think we should bump to version `2.0.0` to cover the breaking change.

@paragbaxi - thoughts?

**Comment by ttzztztz** [comment]
fyi: I've merged this branch to the master to resolve the conflict issue

**Comment by rubengmurray** [comment]
Now available under version `2.0.0` as part of #44

**Pull request merged**
