### PR TITLE
Bump win-dpapi version

### PR DESCRIPTION
**Pull request by daguej**
Fixes native build errors in recent versions of node.

Despite the semver-major bump, I don't believe there's actually any breaking changes.

[Compare changes](https://github.com/daguej/node-dpapi/compare/v0.1.0..v1.1.0)

### CODE REVIEW

**Comment by rubengmurray** [comment]
@paragbaxi I noticed this was merged in on your fork. I'm unable to test on windows but I presume it works well in your version? Tempted to merge this in here.

Could you confirm?

**Comment by rubengmurray** [comment]
@daguej - I've belatedly looked into merging the latest version of `win-dpapi` into this repo, but I'm getting very strange behaviour with Node on windows.

When running the two tests in this PR https://github.com/bertrandom/chrome-cookies-secure/pull/44/files I am getting intermittent hanging when retrieving cookies on Node `18.3.0`, the tests always hang when attempting to retrieve cookies on Node `16.3.1`, and I can always retrieve cookies on `12.18.4`.

Anything you can think of that would cause this?

**Comment by rubengmurray** [comment]
> @daguej - I've belatedly looked into merging the latest version of `win-dpapi` into this repo, but I'm getting very strange behaviour with Node on windows.
> 
> When running the two tests in this PR https://github.com/bertrandom/chrome-cookies-secure/pull/44/files I am getting intermittent hanging when retrieving cookies on Node `18.3.0`, the tests always hang when attempting to retrieve cookies on Node `16.3.1`, and I can always retrieve cookies on `12.18.4`.
> 
> Anything you can think of that would cause this?

I should add, the hanging occurs around the `require` statement inside the `process.platform` evaluation. Something about the `win-dpapi` `require` it doesn't like.

**Edit**: I've adjusted the import at the top of the file to a `const` and been completely rigorous with deleting `node_modules` + `package-lock.json` as I've cycled through the node versions and it appears to now be working on all of them.

Tested on `12.18.4`, `14.18.2`, `16.13.1`, `18.3.0`

**Comment by daguej** [comment]
I'm afraid I have no idea what might cause this behavior, and likely won't have the time to investigate.

**Comment by rubengmurray** [comment]
Now available under version `2.0.0` as part of #44

**Pull request merged**
